/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/drone.glb -o src/components/DroneModel.jsx -t -s -T public/drone-transformed.glb 
Files: public/drone.glb [492KB] > /Users/pham/Desktop/projects/swarm/src/components/drone-transformed.glb [37.46KB] (92%)
*/

import * as THREE from 'three';
import React from 'react';
import { useGLTF } from '@react-three/drei';
import { GLTF } from 'three-stdlib';

export function DroneModel(props) {
  const { nodes, materials } = useGLTF('/drone-transformed.glb');
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube.geometry}
        material={materials.PaletteMaterial001}
      />
      <group position={[0, 0.648, 0]} scale={[1, 1, 1.987]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube001.geometry}
          material={materials.PaletteMaterial004}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube001_1.geometry}
          material={materials.PaletteMaterial002}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube001_2.geometry}
          material={materials.PaletteMaterial003}
        />
      </group>
    </group>
  );
}

useGLTF.preload('/drone-transformed.glb');
